# This is a minimal workflow.

name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello there."

      - name: Run an action
        uses: blairlearn/build-info@main
      #  with:
      #    output-name: 
      
      - name: Goodbye
        run: echo "Bye now!"
          
