# This is a minimal workflow.

name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello there."

      - name: Context dump
        id: dump
        env:
          ID: ${{github.id}}
        uses: actions/github-script@v6
        with:
          script: |
            //console.log(JSON.stringify(context, null, 2));
            console.log('   runNumber: ' + context.runNumber);
            console.log('       runID: ' + context.runId);
            console.log('   github.id: ' + github.id);
            console.log('    actor_id: ' + github.actor_id);
            console.log('      action: ' + github.action);
            console.log(' ');
            console.log(' ');
            console.log('          id: ' + process.env.ID );
            console.log(JSON.stringify(process.env, null, 2));

      - name: get the ip
        id: ip
        run: ifconfig


      - name: I can has Docker?
        run: |
          docker --help

      - name: I can has Compose too?
        run: |
          docker compose --help

      - name: Run an action
        uses: blairlearn/build-info@v1.0.0
        with:
          output-name: build-info-action.json

      - name: dump
        run: cat build-info-action.json

      - name: Old school
        run: |
          ## PUSH
          if [ "${{ github.event_name }}" == "push" ]; then
            BUILD_NAME=$(sed -E 's/refs\/(heads|tags)\///; s/\//__/g;' <<< $GITHUB_REF)
            BRANCH_NAME=$(sed -E 's/refs\/(heads|tags)\///;' <<< $GITHUB_REF)
            COMMIT_HASH=$(echo "${GITHUB_SHA}")
          ## PULL_REQUEST
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            BUILD_NAME=$(echo "pr-${{ github.event.pull_request.number }}")
            BRANCH_NAME=$(echo "pr-${{ github.event.pull_request.number }}")
            COMMIT_HASH=$(echo "${{ github.event.pull_request.head.sha }}")
          else
            ## ERROR
            exit 1
          fi
          ## For step checks and artifact deployment path.
          ## Same for push and PR
          export REPO_FULL=${{ github.repository }}
          export REPO_RE='([^/]+)/(.*)'
          [[ "$REPO_FULL" =~ $REPO_RE ]]
          REPO_OWNER=$(echo "${BASH_REMATCH[1]}")
          REPO_NAME=$(echo "${BASH_REMATCH[2]}")

          echo "build_name: ${BUILD_NAME}"
          echo "branch_name: ${BRANCH_NAME}"
          echo "commit_hash: ${COMMIT_HASH}"
          echo "repo_owner: ${REPO_OWNER}"
          echo "repo_name: ${REPO_NAME}"

      - name: Run an action
        uses: blairlearn/build-info@main
      #  with:
      #    output-name:

      - name: Is Xvfb running?
        run: |
          Xvfb :99&
          while [ ! -e /tmp/.X11-unix/X99 ]; do sleep 0.1; done
          ls -l /tmp/.X11-unix
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload entire directory as an artifact. Bad idea as this includes the .git directory
        uses: actions/upload-artifact@v4
        with:
          name: bad-idea
          path: .

      - name: Goodbye
        run: echo "Bye now!"

