# What happens when a step fails but I want to keep going?

name: Failure tests

on:
    workflow_dispatch:
    push:

jobs:

  run-success-or-failure:
    runs-on: ubuntu-latest

    steps:
      - name: This step fails
        run: exit 1

      - name: This step runs anyhow
        if: ${{ success() || failure() }}
        run: echo 'Hello'

  run-always:
    runs-on: ubuntu-latest

    steps:
      - name: This step fails
        run: exit 1

      - name: This step runs anyhow
        if: ${{ always() }}
        run: echo 'Hello'
